name: hello_world

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.3.0  # Ensure this is the latest compatible version
  characters: ^1.3.0
  collection: ^1.18.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.25.7
  _fe_analyzer_shared: ^72.0.0
  analyzer: ^6.7.0
  args: ^2.5.0
  async: ^2.11.0
  boolean_selector: ^2.1.1
  clock: ^1.1.1
  convert: ^3.1.1
  coverage: ^1.8.0
  crypto: ^3.0.3
  fake_async: ^1.3.1
  file: ^7.0.0
  frontend_server_client: ^4.0.0
  glob: ^2.1.2
  http_multi_server: ^3.2.1
  http_parser: ^4.0.2
  io: ^1.0.4
  js: ^0.7.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker_testing: ^3.0.1
  logging: ^1.2.0
  matcher: ^0.12.16+1
  mime: ^1.0.5
  node_preamble: ^2.0.2
  package_config: ^2.1.0
  path: ^1.9.0
  pool: ^1.5.1
  pub_semver: ^2.1.4
  shelf: ^1.4.1
  shelf_packages_handler: ^3.0.2
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  string_scanner: ^1.2.0
  sync_http: ^0.3.1
  term_glyph: ^1.2.1
  test_api: ^0.7.2
  test_core: ^0.6.4
  typed_data: ^1.3.2
  vm_service: ^14.2.5
  watcher: ^1.1.0
  web: ^0.5.1
  web_socket_channel: ^2.4.5
  webdriver: ^3.0.3
  webkit_inspection_protocol: ^1.2.1
  yaml: ^3.1.2

# PUBSPEC CHECKSUM: 2760
